// <auto-generated />
using ArcticFox.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ArcticFox.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AFDbContext))]
    [Migration("20171127043801_Add_AuditingLog_Table")]
    partial class Add_AuditingLog_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArcticFox.Audiing.AuditingLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Duration");

                    b.Property<string>("Exception");

                    b.Property<DateTime>("ExecutionTime");

                    b.Property<string>("IPAddress");

                    b.Property<string>("Parameters");

                    b.Property<string>("Result");

                    b.Property<string>("ServerName");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("AuditingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
